

- name: install nginx
  package:
    name:
      - nginx
    state: latest

- name: Set selinux to allow proxy_pass
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: upload vhosts
  template:
    src: ../templates/vhosts.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Restart nginx
  service:
    name: nginx
    state: restarted
