- hosts: all
  tasks:
    - name: install good shit
      package:
        name:
          - npm
          - vim
          - httpd
          - mariadb-server
        state: latest
  roles:
    - iptables
    - snap
    - named
