- hosts: all
  tasks:
    - name: install good shit
      package:
        name:
          - npm
          - vim
          - httpd
          - mariadb-server
          - docker  
        state: latest
  roles:
    - firewalld
    - snap
    - named
    - nginx
    - docker
