- hosts: all
  tasks:
    - name: install good shit
      package:
        name:
          - npm
          - vim
          - bind
          - httpd
          - mariadb-server
        state: latest
    
