- hosts: all
  tasks:
    - name: install good shit
      package:
        name:
          - npm
          - vim
          - bind
          - httpd
          - mariadb-server
          - snapd
        state: latest
  roles:
    - snap
  #    - bertvv.bind
  vars:
    bind_dnssec_enable: no
    bind_zone_master_server_ip:
      - '127.0.0.1'
    bind_forwarders:
      - '8.8.8.8'
      - '8.8.4.4'
    bind_zone_domains:
      - name: 'hs3.pl'
        hosts:
          - name: squire
            ip: 10.14.10.4
        networks:
          - '10.14.10'

#ln -s /var/lib/snapd/snap /snap
#
