- name: Set the policy for the INPUT chain to DROP
  iptables:
    chain: INPUT
    policy: ACCEPT

- name: Set the policy for the FORWARD chain to ACCEPT
  iptables:
    chain: FORWARD
    policy: ACCEPT

- name: Set the policy for the OUTPUT chain to DROP
  iptables:
    chain: OUTPUT
    policy: ACCEPT

- name: FLUSH THE IPTABLES!!!!!!
  iptables:
    flush: yes

- name: Allow all incoming HTTP packets that are established.
  iptables:
    chain: INPUT
    protocol: tcp
    ctstate:
      - RELATED # connection appearing from the established
      - ESTABLISHED # connection that got synchronized with host
      - DNAT # if incoming packet changed the incoming interface
    jump: ACCEPT
    comment: Accept established connections.

- name: Allow new incoming SSH packets on TCP port 22.
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '22'
    ctstate:
      - NEW
      - UNTRACKED
    jump: ACCEPT
    comment: Accept new SSH connections.

- name: Allow new incoming HTTP packets on TCP port 8080.
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: '8080'
    ctstate:
      - NEW
      - UNTRACKED
    jump: ACCEPT
    comment: Accept new HTTP connections.

- name: Allow new incoming DNS packets on UDP port 53.
  iptables:
    chain: INPUT
    protocol: udp
    destination_port: '53'
    jump: ACCEPT
    comment: Accept DNS queries.

- name: Drop invalid tcp connections.
  iptables:
    chain: INPUT
    protocol: tcp
    ctstate:
      - INVALID
    jump: REJECT
    comment: Drop invalid connections.
