bind_dnssec_validate: auto
bind_zone_master_server_ip: '{{host}}'
bind_forwarders:
  - '8.8.8.8'
  - '8.8.4.4'
bind_zone_domains:
  - name: 'arthur.at.hs3.pl'
    hosts:
      - name: squire
        ip: '10.14.10.4'
      - name: dns
        ip: '{{host}}'
      - name: events
        ip: '{{host}}'
    name_servers:
      - dns
